### ISSUE TITLE
Minimum iOS platform version requirement

### ISSUE THREAD

**Issue by pushchris** [LeonardoCardoso/DownloadButton#5]
Why has the platform dependency changed to require iOS12? This makes it such that any app that requires supporting a past OS version can't use the Pod even though from a code perspective it still fully supports them. Upgrading to Swift 4.2 shouldn't require a minimum version dependency change from 11 to 12. Could this please be changed back? Jumping from iOS 8 to 12 is a huge change.

**Comment by leonardocardoso** [comment]
Hi, you can use the version `0.0.4` for an older iOS version. This library hasn't reached its stable version `1.0.0` yet. So it might constantly be updated.

**Comment by pushchris** [comment]
Except you can't. The only version that supports Swift 4.2 is the 0.0.5 version which you can't use if your builds target anything lower than iOS 12. In other words, if you wan't to use this pod, your app can only be built to support iOS 12 (whose adoption is less than 30% currently). Anyone who wants to support the larger 70% of iOS users can't use it. I just don't understand this decision especially because from a technical point of view there is zero reason for it. Literally the only change is to make the podspec listed as iOS 11 instead of 12. No other code needs to be changed.

**Comment by leonardocardoso** [comment]
Of course you can! You don't have to use the latest version in any of your projects.
If you have projects that target iOS version lower than 12, you can use the version `0.0.4`. If you have projects with iOS 12 you can use 0.0.5 our even 0.0.4 and add a post install configuration ordering it to be ran with Swift 4.1. No changes have been made except for the update to Swift 4.2, so this is not a big deal. Anyways, I've regressed the library back. You can use `0.0.6` from now on.
